/**
 * Build script that produces a single executable:
 *   out/ShutdownMyPC.exe
 *
 * The exe is a Windows tray application (C#) with:
 * - Built-in HTTP server (HttpListener) serving the frontend SPA
 * - Frontend files embedded directly in the exe as byte arrays
 * - System tray icon with context menu
 * - Power management API (shutdown.exe)
 * - No external dependencies — single file, fully portable
 */

import { $ } from "bun";
import { readdirSync, existsSync, statSync, readFileSync, writeFileSync, unlinkSync, mkdirSync } from "fs";
import { join, relative } from "path";

const ROOT = join(import.meta.dir ?? ".", "out");
const DIST = join(ROOT, "dist");
const TRAY_ICO = join(import.meta.dir ?? ".", "tray", "tray-icon.ico");

console.log("=".repeat(60));
console.log("  🔨 Building Shutdown My PC");
console.log("=".repeat(60));

// ── Step 1: Build frontend ────────────────────────────────────────
console.log("\n📦 Step 1: Building frontend...");
await $`bun run build:frontend`.quiet();
console.log("   ✅ Frontend built successfully");

if (!existsSync(DIST)) {
  console.error("   ❌ dist/ directory not found after build!");
  process.exit(1);
}

// ── Step 2: Generate EmbeddedFiles.cs ──────────────────────────────
console.log("\n📦 Step 2: Embedding frontend files...");

function collectFiles(dir, baseDir) {
  const entries = [];
  for (const name of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, name.name);
    if (name.isDirectory()) {
      entries.push(...collectFiles(fullPath, baseDir));
    } else {
      entries.push(fullPath);
    }
  }
  return entries;
}

const allFiles = collectFiles(DIST, DIST);
const relPaths = allFiles.map(f => relative(DIST, f).replace(/\\/g, '/'));

let embeddedCs = `// Auto-generated by build.js — do not edit manually
using System;

namespace ShutdownPcTray
{
    static class EmbeddedFiles
    {
        public static void Setup()
        {
            var files = new System.Collections.Generic.Dictionary<string, byte[]>();
`;

for (let i = 0; i < allFiles.length; i++) {
  const data = readFileSync(allFiles[i]);
  const path = relPaths[i];
  const varName = `_f${i}`;

  // Generate byte array
  const bytesStr = Array.from(data).join(",");
  embeddedCs += `            byte[] ${varName} = new byte[] { ${bytesStr} };\n`;
  embeddedCs += `            files["${path}"] = ${varName};\n`;
}

embeddedCs += `
            foreach (var kv in files)
                StaticFiles.Register(kv.Key, kv.Value);
        }
    }
}
`;

const EMBEDDED_FILE = join(import.meta.dir ?? ".", "tray", "EmbeddedFiles.cs");
writeFileSync(EMBEDDED_FILE, embeddedCs);

const fileCount = allFiles.length;
const totalBytes = allFiles.reduce((sum, f) => sum + statSync(f).size, 0);
console.log(`   ✅ ${fileCount} files embedded (${(totalBytes / 1024).toFixed(0)} KB)`);

// ── Step 3: Compile tray app ──────────────────────────────────────
console.log("\n🔧 Step 3: Compiling tray app...");
const CSC = "C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\csc.exe";
const TRAY_DIR = join(import.meta.dir ?? ".", "tray");
const FINAL_OUT = join(ROOT, "ShutdownMyPC.exe");

let trayBuilt = false;

if (existsSync(CSC)) {
  const sources = readdirSync(TRAY_DIR)
    .filter(f => f.endsWith(".cs"))
    .map(f => join(TRAY_DIR, f));

  const result = await $`"${CSC}" -target:winexe -win32icon:"${TRAY_ICO}" -reference:System.Windows.Forms.dll -reference:System.Drawing.dll -reference:System.Net.Http.dll -reference:Microsoft.VisualBasic.dll -out:"${FINAL_OUT}" ${sources}`.nothrow().quiet();

  if (result.exitCode === 0 && existsSync(FINAL_OUT)) {
    const kb = statSync(FINAL_OUT).size / 1024;
    console.log(`   ✅ Tray app compiled (${kb.toFixed(1)} KB)`);
    trayBuilt = true;
  } else {
    console.error(`   ⚠️  Tray compilation failed (exit ${result.exitCode})`);
  }
}

if (!trayBuilt) {
  console.error("\n   ❌ Build failed — cannot produce output.");
  process.exit(1);
}

// ── Step 4: Cleanup temp files ────────────────────────────────────
try { unlinkSync(join(TRAY_DIR, "ServerSize.cs")); } catch {}
try { unlinkSync(join(TRAY_DIR, "EmbeddedFiles.cs")); } catch {}
try { unlinkSync(join(ROOT, ".server.tmp.exe")); } catch {}
try { unlinkSync(join(ROOT, ".tray.tmp")); } catch {}

// ── Summary ───────────────────────────────────────────────────────
const finalSize = statSync(FINAL_OUT).size;
console.log(`\n✅ Build complete!`);
console.log(`   ${join("out", "ShutdownMyPC.exe")} (${(finalSize / 1024 / 1024).toFixed(1)} MB)`);
console.log(`   Frontend files embedded: ${fileCount} (${(totalBytes / 1024).toFixed(0)} KB)`);
console.log(`   Run: ./out/ShutdownMyPC.exe`);
