using System;
using System.Collections.Generic;
using System.IO;

namespace ShutdownPcTray
{
    /// <summary>
    /// Serves embedded static files (HTML, CSS, JS) from in-memory storage.
    /// Files are embedded at compile time via EmbeddedFiles.cs (auto-generated by build.js).
    /// </summary>
    static class StaticFiles
    {
        /// <summary>
        /// Returns the content of a file by its relative path (e.g. "index.html").
        /// Returns null if not found.
        /// </summary>
        public static byte[] Read(string relativePath)
        {
            if (string.IsNullOrEmpty(relativePath))
                return null;
            relativePath = relativePath.Replace('\\', '/');
            byte[] data;
            if (_files.TryGetValue(relativePath, out data))
                return data;
            return null;
        }

        public static bool Exists(string relativePath)
        {
            return Read(relativePath) != null;
        }

        public static string GetMimeType(string path)
        {
            string ext = (Path.GetExtension(path) ?? "").ToLowerInvariant();
            string mime;
            if (_mimeMap.TryGetValue(ext, out mime))
                return mime;
            return "application/octet-stream";
        }

        /// <summary>
        /// Called by EmbeddedFiles.Setup() to register all files at startup.
        /// </summary>
        public static void Register(string relativePath, byte[] data)
        {
            _files[relativePath] = data;
        }

        private static readonly Dictionary<string, byte[]> _files = new Dictionary<string, byte[]>();

        private static readonly Dictionary<string, string> _mimeMap = new Dictionary<string, string>
        {
            { ".html", "text/html; charset=utf-8" },
            { ".css", "text/css; charset=utf-8" },
            { ".js", "application/javascript; charset=utf-8" },
            { ".svg", "image/svg+xml" },
            { ".png", "image/png" },
            { ".ico", "image/x-icon" },
            { ".json", "application/json" },
            { ".woff2", "font/woff2" },
            { ".woff", "font/woff" },
            { ".ttf", "font/ttf" },
        };
    }
}
